<h1>Tabla de Contenidos<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Preparación-de-los-Datos:" data-toc-modified-id="Preparación-de-los-Datos:-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Preparación de los Datos:</a></span><ul class="toc-item"><li><span><a href="#Limpieza-de-los-Datos" data-toc-modified-id="Limpieza-de-los-Datos-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Limpieza de los Datos</a></span></li></ul></li><li><span><a href="#SimpleImputer-de-sklearn" data-toc-modified-id="SimpleImputer-de-sklearn-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>SimpleImputer de sklearn</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Ejemplo-1" data-toc-modified-id="Ejemplo-1-2.0.1"><span class="toc-item-num">2.0.1&nbsp;&nbsp;</span>Ejemplo 1</a></span></li><li><span><a href="#Ejercicio-1" data-toc-modified-id="Ejercicio-1-2.0.2"><span class="toc-item-num">2.0.2&nbsp;&nbsp;</span>Ejercicio 1</a></span></li><li><span><a href="#Respuesta-Ejercicio-1" data-toc-modified-id="Respuesta-Ejercicio-1-2.0.3"><span class="toc-item-num">2.0.3&nbsp;&nbsp;</span>Respuesta Ejercicio 1</a></span></li><li><span><a href="#Ejercicio-2" data-toc-modified-id="Ejercicio-2-2.0.4"><span class="toc-item-num">2.0.4&nbsp;&nbsp;</span>Ejercicio 2</a></span></li><li><span><a href="#Respuesta-Ejercicio-2" data-toc-modified-id="Respuesta-Ejercicio-2-2.0.5"><span class="toc-item-num">2.0.5&nbsp;&nbsp;</span>Respuesta Ejercicio 2</a></span></li><li><span><a href="#Ejercicio-3" data-toc-modified-id="Ejercicio-3-2.0.6"><span class="toc-item-num">2.0.6&nbsp;&nbsp;</span>Ejercicio 3</a></span></li><li><span><a href="#Respuesta-Ejercicio-3:" data-toc-modified-id="Respuesta-Ejercicio-3:-2.0.7"><span class="toc-item-num">2.0.7&nbsp;&nbsp;</span>Respuesta Ejercicio 3:</a></span></li><li><span><a href="#Ejercicio-4" data-toc-modified-id="Ejercicio-4-2.0.8"><span class="toc-item-num">2.0.8&nbsp;&nbsp;</span>Ejercicio 4</a></span></li><li><span><a href="#Respuesta-Ejercicio-4:" data-toc-modified-id="Respuesta-Ejercicio-4:-2.0.9"><span class="toc-item-num">2.0.9&nbsp;&nbsp;</span>Respuesta Ejercicio 4:</a></span></li></ul></li></ul></li></ul></div>

![IES21](img/logo_ies.png)

# Situación Profesional 4: Preparación de los Datos

In [3]:
import numpy as np
import pandas as pd

## Preparación de los Datos:

La preparación de los datos inlcuye tareas como:  

1. Limpieza de los Datos (Data Cleaning)
2. Normalización de los Datos
3. Estandarización de los Datos

En alguna bibliografía se denomina a este proceso **"Curación o Curado de los Datos"**. 
 
Este proceso será distinto en cada trabajo y dependerá:  

- del mismo conjunto de datos, y   
- del **modelo** de Machine Learning que vayamos a usar, ya que **algunos modelos requieren cierto tratamiento** para funcionar correctamente, mientras que otros no.


En sklearn ver: https://scikit-learn.org/stable/data_transforms.html

### Limpieza de los Datos

El problema principal con respecto a data cleaning es qué hacer o cómo proceder con los valores **nulos**. Muchos algoritmos de ML **no permiten** el procesamiento de valores nulos.  

Afortunadamente Pandas y Scikit-Learn nos provee de varias funciones que nos permitirán resolver los problemas más habituales, entre ellos el de **imputar** o asignar algún valor a los elementos **nulos**.

## SimpleImputer de sklearn

Como decíamos una estrategia para trabajar con los valores nulos es asignarles algún valor; si la variable es numérica lo más habitual es asignarles el valor de la media, la mediana u otro que nos resulte de conveniencia; en el caso que la variable sea categórica, se suele asignar el valor de la moda, es decir la categoría que se repite una mayor cantidad de veces.

Si bien es posible efectuar estas imputaciones utilizando las herramientas que nos brindan Numpy o Pandas, Scikit-Learn tiene una herramienta más práctica: **SimpleImputer**, que se encuentra en la librería **sklearn.impute**. 

La documentación oficial se encuentra en: https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html

y una explicación sobre su funcionamiento se encuentra en:  
https://scikit-learn.org/stable/modules/impute.html

Vamos a aprender a usar esta potene herramienta y más adelante veremos cómo agregarla en nuestro flujo de trabajo de Machine Learning.  


Carguémosla: 

In [1]:
from sklearn.impute import SimpleImputer

La sintaxis es:   

sklearn.impute.SimpleImputer(*, missing_values=nan, strategy='mean', fill_value=None, verbose=0, copy=True, add_indicator=False)  

Un comentario sobre las opciones más importantes:   


- En **_missing_values_** debemos indicar qué valor identifica a los "valores nulos" en los datos; generalmente serán valores nan (el valor por defecto), pero circunstancialmente se utilizan otros valores como por ejemplo el 0 (recuerda la base de datos de calificaciones de películas que usamos en la materia Computación Científica? En esa base de datos el 0 indicaba la ausencia de calificación), en otros casos, por ejemplo cuando los valores de la variable deben ser positivos (altura de una persona, por ejemplo) se suele utilizar un valor negativo como -1 para las mediciones faltantes. Depende de la fuente de datos.   


- En **_strategy_** debemos indicar con qué valor se reemplazarán los nulos, los valores posibles son:  
    - 'mean' (el valor por defecto) se puede usar cuando los valores son numéricos
    - 'median' si queremos que impute la mediana, también se usa cuando los valores son numéricos
    - 'most_frequent' para indicar que queremos que utilice la moda, cuando la variable no es numérica. 
    - 'constant' si queremos indicar otro valor que no sea ninguo de los anteriores por alguna conveniencia. Si optamos por ésta, entonces podemos indicar en **_fill_value_** el valor con que deseamos reemplazar los nulos, si lo dejamos vacío cargará 0.  
    
    
- En **_copy_**: Si indicamos True, el valor por defecto, significa que se creará una copia de los valores X y no se alterarán los datos originales, si se indica False entonces el reemplazo se hará sobre los valores originales.

     


#### Ejemplo 1

Primero, un ejemplo sencillo del uso del imputador.  

Supongamos que tenemos el siguiente DataFrame:

In [3]:
dfA=pd.DataFrame([[1,3,2],[np.nan,5,7],[3,np.nan,8],[np.nan,4,3]])
dfA.columns=['col1','col2','col3']
dfA

col1  col2  col3
0   1.0   3.0     2
1   NaN   5.0     7
2   3.0   NaN     8
3   NaN   4.0     3

y supongamos que deseamos asignar o imputar la media o promedio de cada columna a los valores NaN existentes en cada columna.   

Este es un proceso ode 3 pasos:

1. **Creación**: Primero debemos crear el imputador con las características deseadas, en este caso sólo le indicaremos la estrategia.

In [4]:
imputador=SimpleImputer(strategy="mean")

2. **Entrenamiento**: como segundo paso debemos indicarle a qué datos debe calcular la media. Usaremos el método **fit**

In [5]:
imputador.fit(dfA)

SimpleImputer()

En este momento lo único que ha hecho nuestro imputador es calcular los promedios para cada columna, si lo necesitamos, podemos ver estos valores de la siguiente manera: 

In [6]:
imputador.statistics_

array([2., 4., 5.])

Como podemos observar simplemente calculó los promedios de cada columna sin tener en cuenta los nan.   

3. **Aplicación**: el último paso consiste en aplicar el imputador a algún dataset, en este caso será al mismo dataset dfA para que cambie los valores NaN por los promedios. Usaremos el método **transform**

In [7]:
imputador.transform(dfA)

array([[1., 3., 2.],
       [2., 5., 7.],
       [3., 4., 8.],
       [2., 4., 3.]])

Como podemos ver, cambió los dos valores nan que habia en la primer columna por el promedio que era 2, en la segunda columna cambió el único nan por 5 y en la tercer columna que no tenía ningún nan no hizo nada.  

Un par de observaciones:  

1. Esta operación **no** modificó los datos originales, los preservó (por las dudas), fíjese:

In [8]:
dfA

col1  col2  col3
0   1.0   3.0     2
1   NaN   5.0     7
2   3.0   NaN     8
3   NaN   4.0     3

Así que si queremos guardar los resultados *transformados*, es decir con los valores imputados, deberíamos asignarlos a una nueva variable:

In [9]:
A_Transformado=imputador.transform(dfA)
A_Transformado

array([[1., 3., 2.],
       [2., 5., 7.],
       [3., 4., 8.],
       [2., 4., 3.]])

2. El resultado **no** es un DataFrame de Pandas, sino que es un array de Numpy. Si necesitamos que sea un DataFrame, deberíamos pasarle este array como dato y pasarle también el nombre de las columnas (un poco pesado, pero no siempre necesitaremos que esta salida sea un DataFrame de Pandas!).   

Si lo necesitamos, podríamos proceder así: 

In [10]:
dfA_Transformado=pd.DataFrame(A_Transformado)  # le pasamos los datos
dfA_Transformado.columns=dfA.columns           # le pasamos los nombres de las columnas de dfA
dfA_Transformado

col1  col2  col3
0   1.0   3.0   2.0
1   2.0   5.0   7.0
2   3.0   4.0   8.0
3   2.0   4.0   3.0

3. Observe que el imputador actuó sobre **todas** las columnas, esto puede significar un enorme ahorro de tiempo si tenemos muchas columnas a las cuales queremos transformar asignando el promedio a sus valores nan.  

#### Ejercicio 1

Supongamos que tenemos el dataframe dfB, y queremos imputar o asignar el valor de la **mediana** a los valores nulos (nan) de todas sus columnas.   
Al imputador llámelo imputador1 y guarde los resultados ya transformados en un DataFrame denominado dfB_Transformado.

In [4]:
dfB=pd.DataFrame([[1,5,4,3],[np.nan,3,2,np.nan],[7,np.nan,0,4],[4,2,4,1],[3,0,np.nan,8],[2,7,5,4]])
dfB.columns=['col1','col2','col3','col4']
dfB

col1  col2  col3  col4
0   1.0   5.0   4.0   3.0
1   NaN   3.0   2.0   NaN
2   7.0   NaN   0.0   4.0
3   4.0   2.0   4.0   1.0
4   3.0   0.0   NaN   8.0
5   2.0   7.0   5.0   4.0

#### Respuesta Ejercicio 1

En forma corta el flujo serían nuestros 3 pasos, crear el imputador, entrenarlo y aplicarlo:

In [12]:
imputador1=SimpleImputer(missing_values=np.nan,strategy='median') # creamos
imputador1.fit(dfB)                                               # entrenamos
B_Transformado=imputador1.transform(dfB)                          # imputamos

B_Transformado

array([[1., 5., 4., 3.],
       [3., 3., 2., 4.],
       [7., 3., 0., 4.],
       [4., 2., 4., 1.],
       [3., 0., 4., 8.],
       [2., 7., 5., 4.]])

Hemos obtenido los valores ya transformados pero como array de Numpy, si es necesario podemos transformarlo en un dataFrame con los mismos nombres de columnas que el original.

In [13]:
# lo que sigue es sólo para rearmarlo como DataFrame, si es necesario y luego mostrarlo:
dfB_Transformado=pd.DataFrame(B_Transformado, columns=dfB.columns)
dfB_Transformado

col1  col2  col3  col4
0   1.0   5.0   4.0   3.0
1   3.0   3.0   2.0   4.0
2   7.0   3.0   0.0   4.0
3   4.0   2.0   4.0   1.0
4   3.0   0.0   4.0   8.0
5   2.0   7.0   5.0   4.0

Como puede observar, realmente muy sencillo! Veamos algunos casos más.

#### Ejercicio 2  

Dado el DataFrame dfC, impute la mediana de cada columna a los valores que tienen valor -1. Al imputador llámelo imputador2 y guarde los resultados en un nuevo dataFrame denominado dfC_Transformado

In [5]:
dfC=pd.DataFrame([[3,7,-1,0],[2,-1,5,4],[0,0,0,0],[-1,5,4,2],[2,6,8,1],[2,1,3,2]])
dfC.columns=['A','B','C','D']
dfC

A  B  C  D
0  3  7 -1  0
1  2 -1  5  4
2  0  0  0  0
3 -1  5  4  2
4  2  6  8  1
5  2  1  3  2

#### Respuesta Ejercicio 2

En forma corta el flujo sería:

In [8]:
# Escriba aquí su código
imputador2=SimpleImputer(missing_values=-1,strategy='median') # creamos
imputador2.fit(dfC)                                               # entrenamos
C_Transformado=imputador2.transform(dfC)                          # imputamos

C_Transformado

array([[3., 7., 4., 0.],
       [2., 5., 5., 4.],
       [0., 0., 0., 0.],
       [2., 5., 4., 2.],
       [2., 6., 8., 1.],
       [2., 1., 3., 2.]])

In [9]:
# Para rearmarlo como DataFrame:
dfC_Transformado=pd.DataFrame(C_Transformado, columns=dfC.columns)
dfC_Transformado

A    B    C    D
0  3.0  7.0  4.0  0.0
1  2.0  5.0  5.0  4.0
2  0.0  0.0  0.0  0.0
3  2.0  5.0  4.0  2.0
4  2.0  6.0  8.0  1.0
5  2.0  1.0  3.0  2.0

#### Ejercicio 3  
Vamos a complicarla un poco:  
    

Dado el DataFrame dfC: 

- En las columnas A y C, impute a los valores -1, el promedio. Llame a este imputador imputador_prom
- En las columnas B y D impute a los valores -1 la mediana. Llame a este imputador imputador_mediana

Guarde los resutados en un nuevo DataFrame denominado dfC_Transformado2

#### Respuesta Ejercicio 3:

Como el imputador de sklearn trabaja sobre **todas** las columnas ... y queremos hacer imputaciones distintas a algunas columnas ... deberemos dividir nuestro dataframe original en dos partes, uno que tenga las columnas A y C y otro que tenga las columnas B y D.

In [10]:
dfC1=dfC[['A','C']] #Separo df en columna A y C
dfC1

A  C
0  3 -1
1  2  5
2  0  0
3 -1  4
4  2  8
5  2  3

Ahora trabajamos con las imputaciones para estas columnas:

In [13]:
# Escriba aquí su código
# Escriba aquí su código
imputador_prom=SimpleImputer(missing_values=-1,strategy='mean') # creamos
imputador_prom.fit(dfC1)                                               # entrenamos
C1_Transformado=imputador_prom.transform(dfC1)                          # imputamos

C1_Transformado

array([[3. , 4. ],
       [2. , 5. ],
       [0. , 0. ],
       [1.8, 4. ],
       [2. , 8. ],
       [2. , 3. ]])

Ahora repetimos las operaciones para las columnas B y D:

In [11]:
# Escriba aquí su código
#Separo df en columna en B y D
dfC2=dfC[['B','D']]
dfC2

B  D
0  7  0
1 -1  4
2  0  0
3  5  2
4  6  1
5  1  2

Ahora trabajamos con las imputaciones para estas columnas:

In [14]:
# Escriba aquí su código
imputador_mediana=SimpleImputer(missing_values=-1,strategy='median') # creamos
imputador_mediana.fit(dfC2)                                               # entrenamos
C2_Transformado=imputador_mediana.transform(dfC2)                          # imputamos

C2_Transformado

array([[7., 0.],
       [5., 4.],
       [0., 0.],
       [5., 2.],
       [6., 1.],
       [1., 2.]])

Si lo necesitamos (no siempre es necesario), podríamos reconstruir el DataFrame con todas sus columnas pero ahora transformadas, para ello deberemos  utilizar un poco de Pandas ... podemos usar pd.concat() ... (hay muchas otras formas de hacerlo):

In [19]:
# Para rearmarlo como DataFrame:
dfC1_Transformado=pd.DataFrame(C1_Transformado, columns=dfC1.columns)
dfC1_Transformado

A    C
0  3.0  4.0
1  2.0  5.0
2  0.0  0.0
3  1.8  4.0
4  2.0  8.0
5  2.0  3.0

In [20]:
# Para rearmarlo como DataFrame:
dfC2_Transformado=pd.DataFrame(C2_Transformado, columns=dfC2.columns)
dfC2_Transformado

B    D
0  7.0  0.0
1  5.0  4.0
2  0.0  0.0
3  5.0  2.0
4  6.0  1.0
5  1.0  2.0

In [29]:
# Concateno ambos df ya transformados
df_concat=pd.concat([dfC1_Transformado,dfC2_Transformado],ignore_index=True, sort = False, axis=1)
df_concat

0    1    2    3
0  3.0  4.0  7.0  0.0
1  2.0  5.0  5.0  4.0
2  0.0  0.0  0.0  0.0
3  1.8  4.0  5.0  2.0
4  2.0  8.0  6.0  1.0
5  2.0  3.0  1.0  2.0

In [31]:
#Arrego nombre de las columnas del nuevo df concatenado y con los datos arreglados
df_concat.columns=['A','C','B','D']
df_concat

A    C    B    D
0  3.0  4.0  7.0  0.0
1  2.0  5.0  5.0  4.0
2  0.0  0.0  0.0  0.0
3  1.8  4.0  5.0  2.0
4  2.0  8.0  6.0  1.0
5  2.0  3.0  1.0  2.0

#### Ejercicio 4

Supongamos que tenemos un DataFrame como el dfD:

In [32]:
dfD=pd.DataFrame([[3,2,'Si'],[np.nan,6,'No'],[5,8,'Si'],[0,np.nan,'Si'],[np.nan,4,'No'],[6,6,np.nan],[4,12,'No'],[2,9,np.nan]])
dfD.columns=['x1','x2','x3']
dfD

x1    x2   x3
0  3.0   2.0   Si
1  NaN   6.0   No
2  5.0   8.0   Si
3  0.0   NaN   Si
4  NaN   4.0   No
5  6.0   6.0  NaN
6  4.0  12.0   No
7  2.0   9.0  NaN

Observe que la variable x3 no es numérica, sino categórica.

Queremos imputar el promedio en las columnas numéricas y la moda en las columnas categóricas (esto es un problema bien típico de ML).  Queremos el resultado en un único DataFrame que se llame dfD_Transformado.


#### Respuesta Ejercicio 4:

Podríamos comenzar separando las columnas numéricas por un lado y las categóricas por otro.  

A continuación separe en un nuevo dataframe las variables numéricas: 

In [33]:
# Escriba aquí su código para las variables numéricas
dfD_num=dfD[['x1','x2']] #Separo df en columna A y C
dfD_num

x1    x2
0  3.0   2.0
1  NaN   6.0
2  5.0   8.0
3  0.0   NaN
4  NaN   4.0
5  6.0   6.0
6  4.0  12.0
7  2.0   9.0

Ahora vamos con la única variable categórica (como es una sola, nos traerá un poco de problema ...)

In [23]:
dfD_cat_=dfD['x3']
dfD_cat_

0     Si
1     No
2     Si
3     Si
4     No
5    NaN
6     No
7    NaN
Name: x3, dtype: object

Observar que **como el resultado es una sola columna**, el resultado no es un dataFrame, sino una Serie de Pandas, y como al usar el imputer nos pide que sea de 2 dimensiones, lo vamos a arreglar ahora; en vez de la línea anterior podríamos haber usado:

In [34]:
dfD_cat=pd.DataFrame()     # lo definimmos como un dataFrame
dfD_cat['x3']=dfD['x3']    # en la columna x3 del nuevo DataFrame, cargamos los valores 
dfD_cat

x3
0   Si
1   No
2   Si
3   Si
4   No
5  NaN
6   No
7  NaN

Vamos a imputar a las columnas numéricas:

In [36]:
# Escriba aquí su código
imputador_num=SimpleImputer(missing_values=np.nan,strategy='mean') # creamos
imputador_num.fit(dfD_num)                                               # entrenamos
Num_Trans=imputador_num.transform(dfD_num)                          # imputamos

Num_Trans

array([[ 3.        ,  2.        ],
       [ 3.33333333,  6.        ],
       [ 5.        ,  8.        ],
       [ 0.        ,  6.71428571],
       [ 3.33333333,  4.        ],
       [ 6.        ,  6.        ],
       [ 4.        , 12.        ],
       [ 2.        ,  9.        ]])

Ahora vamos con la columna categórica

In [38]:
imputador_cat=SimpleImputer(missing_values=np.nan,strategy='most_frequent') # creamos
imputador_cat.fit(dfD_cat)                                               # entrenamos
Cat_Trans=imputador_cat.transform(dfD_cat)                          # imputamos

Cat_Trans

array([['Si'],
       ['No'],
       ['Si'],
       ['Si'],
       ['No'],
       ['No'],
       ['No'],
       ['No']], dtype=object)

Finalmente si deseamos juntar ambos DataFrames en uno solo:

In [39]:
# Escriba aquí su código
dfNum=pd.DataFrame(Num_Trans, columns=dfD_num.columns)
dfNum

x1         x2
0  3.000000   2.000000
1  3.333333   6.000000
2  5.000000   8.000000
3  0.000000   6.714286
4  3.333333   4.000000
5  6.000000   6.000000
6  4.000000  12.000000
7  2.000000   9.000000

In [40]:
dfCat=pd.DataFrame(Cat_Trans, columns=dfD_cat.columns)
dfCat

x3
0  Si
1  No
2  Si
3  Si
4  No
5  No
6  No
7  No

In [43]:
dfD_Transformado=pd.concat([dfNum,dfCat],ignore_index=True, sort = False, axis=1)
dfD_Transformado.columns=['x1','x2','x3']
dfD_Transformado

x1         x2  x3
0  3.000000   2.000000  Si
1  3.333333   6.000000  No
2  5.000000   8.000000  Si
3  0.000000   6.714286  Si
4  3.333333   4.000000  No
5  6.000000   6.000000  No
6  4.000000  12.000000  No
7  2.000000   9.000000  No