In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('data/Social_Network_Ads.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [24]:
X=df[['Age','EstimatedSalary']]
y=df['Purchased']


In [8]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [25]:
X_train, X_test,y_train, y_test=train_test_split(X,y, test_size=0.2, random_state=123)

In [39]:
modelo=LogisticRegression(penalty='none', random_state=123)

In [40]:
modelo.fit(X_train,y_train)

LogisticRegression(penalty='none', random_state=123)

In [41]:
ACC=modelo.score(X_test,y_test)
ACC

0.625

In [31]:
modelo.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [44]:
probas=modelo.predict_proba(X_test)
probas

array([[0.5881269 , 0.4118731 ],
       [0.58504168, 0.41495832],
       [0.56248849, 0.43751151],
       [0.51192504, 0.48807496],
       [0.5515015 , 0.4484985 ],
       [0.53967398, 0.46032602],
       [0.5459884 , 0.4540116 ],
       [0.6080024 , 0.3919976 ],
       [0.56874006, 0.43125994],
       [0.59120519, 0.40879481],
       [0.53413831, 0.46586169],
       [0.5617056 , 0.4382944 ],
       [0.55150152, 0.44849848],
       [0.53492965, 0.46507035],
       [0.54756479, 0.45243521],
       [0.55700199, 0.44299801],
       [0.56639815, 0.43360185],
       [0.52621594, 0.47378406],
       [0.54046402, 0.45953598],
       [0.5515015 , 0.4484985 ],
       [0.51748622, 0.48251378],
       [0.54914022, 0.45085978],
       [0.5135143 , 0.4864857 ],
       [0.59274167, 0.40725833],
       [0.56327105, 0.43672895],
       [0.6057259 , 0.3942741 ],
       [0.54125385, 0.45874615],
       [0.61178608, 0.38821392],
       [0.54677672, 0.45322328],
       [0.55935512, 0.44064488],
       [0.

In [98]:
umbral_0=0.527 # que pronostique 0 si la probabilidad es mayor que 0.57
y_pred_umbral=[]

for i in np.arange(0,probas.shape[0]):
    if probas[i][0]>umbral_0:
        y_pred_agregar=0
    else:
        y_pred_agregar=1
    
    y_pred_umbral.append(y_pred_agregar)
    
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
ACC_umbral=accuracy_score(y_test,y_pred_umbral)
print(ACC_umbral)
confusion_matrix(y_test,y_pred_umbral)

0.5875


array([[41,  9],
       [24,  6]], dtype=int64)

0.3125